### ISSUE TITLE
Suggest to publish with a license.

### ISSUE THREAD

**Issue by xfguo** [sifive/last-week-in-risc-v#6]
Nice job, my suggestion is apply a license, like CC-BY-NC-SA.

----

Also please take a look at cnrv.io and https://github.com/cnrv/home for **bi-weekly report** in Chinese published by CC-BY-NC-SA.

We are very happy to translate or reference part of this LWIRV report, we may back port any other Asia Pacific news to here too.

**Comment by palmer-dabbelt** [comment]
Makes sense.  I've gone ahead and adopted the same license you have, as it seems reasonable.  As far as I can tell it just lets anyone use the text for anything, which is really the purpose of this newsletter.

https://github.com/sifive/last-week-in-risc-v/commit/8a6978809c5e5432d7959b2e0fb3700388ac9a12

I'd be happy to sync up with the Chinese newsletter, but since I can't read Chinese I'll need you to help out.  Feel free to open pull requests for anything I appear to be missing, events in particular would be very easy to sync up on.  I'm usually done by Friday morning when I send it out for publishing, but if we're a week behind on some news it's not a big deal.

Thanks!

**Comment by palmer-dabbelt** [comment]
Whoops, I didn't actually include the license text in that commit :).  This should actually do it: https://github.com/sifive/last-week-in-risc-v/commit/3925509badbf880b46baf76f8076cace59ba0e06

**Comment by xfguo** [comment]
Don't worry about Chinese, we will open a PR directly for contents.

**Comment by palmer-dabbelt** [comment]
Great, thanks!
